name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: pimterry/docker-registry-facade,ghcr.io/httptoolkit/docker-registry-facade
          tags:
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update production container to latest image version
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: thibaultchazal/scaleway-serverless-container-deploy-action@main
        with:
          container_id: ${{ vars.SCW_API_CONTAINER_ID }}
          secret_key: ${{ secrets.SCW_SECRET_KEY }}
          registry_image_url: "ghcr.io/httptoolkit/docker-registry-facade:main"

      - name: Update Docker Hub repo description
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'ref/tags/')
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: pimterry/docker-registry-facade
          short-description: ${{ github.event.repository.description }}